# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rtmx < Formula
  desc "Requirements Traceability Matrix toolkit"
  homepage "https://rtmx.ai"
  version "1.12.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rtmx-ai/rtmx/releases/download/v1.12.2/rtmx_1.12.2_darwin_amd64.tar.gz"
      sha256 "3c43c64c1fcbcad0a39fd594ffbf5e236443257a77f7cebe4f3f9edf39817971"

      define_method(:install) do
        bin.install "rtmx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rtmx-ai/rtmx/releases/download/v1.12.2/rtmx_1.12.2_darwin_arm64.tar.gz"
      sha256 "4b2af93ae6538d9d5978592857f5c1a3635a53e87554f84d0be08eb69f6abbf6"

      define_method(:install) do
        bin.install "rtmx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtmx-ai/rtmx/releases/download/v1.12.2/rtmx_1.12.2_linux_amd64.tar.gz"
      sha256 "1af051b09a17dc8d6db69527b20ea8ea5d61af2610c523ebe1619e2c93a52ee4"
      define_method(:install) do
        bin.install "rtmx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtmx-ai/rtmx/releases/download/v1.12.2/rtmx_1.12.2_linux_arm64.tar.gz"
      sha256 "d28a637b227948684df415b9222f0b2248399921f594c2c66d1c1e1c730683ad"
      define_method(:install) do
        bin.install "rtmx"
      end
    end
  end

  test do
    system "#{bin}/rtmx", "version"
  end
end
